name: 3DeeCellTracker-binder
channels:
  - conda-forge
dependencies:
  - python=3.10
  - tensorflow=2.11
  - pip
  - pip:
      - 3DeeCellTracker==1.0.1
      - csbdeep==0.8.1
      - stardist==0.8.3
      - matplotlib~=3.8.4


